### ISSUE TITLE
Attribute filter data profile -- difficult to read on white themes

### ISSUE THREAD

**Issue by kvistgaard** [GitMurf/roam-javascript#93]
![image](https://user-images.githubusercontent.com/7572721/103642005-d686c080-4f52-11eb-8931-87a5ca415488.png)

**Comment by GitMurf** [comment]
@kvistgaard just made an update to default to red (https://github.com/GitMurf/roam-javascript/commit/fd7220295a0dc39e5814a211afdc9f6c6fb13f99). Also I made sure the HTML element had an id so that you can easily target and override with your own css / theme.

![image](https://user-images.githubusercontent.com/64155612/104496320-aad88b80-558d-11eb-901f-6a13816e3f9d.png)
